version     = "0.1.0"
author      = "treeform"
description = "A cozy multiplayer garden dinner game."
license     = "MIT"

srcDir = "src"
bin = @["heartleaf"]

requires "nim >= 2.2.4"
requires "bitworld >= 0.1.0"
requires "pixie"
requires "mummy >= 0.4.7"
requires "curly"
requires "crunchy"
requires "pathy"
requires "silky >= 0.0.2"
requires "supersnappy >= 2.1.3"
requires "whisky >= 0.1.3"
requires "windy >= 0.4.4"
requires "zippy"
