/* exit */

position: absolute;
width: 31px;
height: 24px;
left: 110px;
top: 50px;

background: #000000;


/* diner */

position: absolute;
width: 9px;
height: 9px;
left: 169px;
top: 107px;

background: #FF0000;


/* diner */

position: absolute;
width: 9px;
height: 9px;
left: 146px;
top: 128px;

background: #FF0000;


/* diner */

position: absolute;
width: 9px;
height: 9px;
left: 145px;
top: 152px;

background: #FF0000;


/* diner */

position: absolute;
width: 9px;
height: 9px;
left: 169px;
top: 176px;

background: #FF0000;


/* diner */

position: absolute;
width: 9px;
height: 9px;
left: 193px;
top: 152px;

background: #FF0000;


/* diner */

position: absolute;
width: 9px;
height: 9px;
left: 192px;
top: 128px;

background: #FF0000;


/* cook */

position: absolute;
width: 9px;
height: 9px;
left: 173px;
top: 69px;

background: #44FF00;


/* wash */

position: absolute;
width: 9px;
height: 9px;
left: 78px;
top: 62px;

background: #44FF00;
