


/* houses */

position: absolute;
width: 525px;
height: 694px;
left: 88px;
top: 129px;



/* house2 */

position: absolute;
width: 31px;
height: 24px;
left: 88px;
top: 536px;

background: #000000;


/* house3 */

position: absolute;
width: 31px;
height: 24px;
left: 127px;
top: 337px;

background: #000000;


/* house4 */

position: absolute;
width: 31px;
height: 24px;
left: 170px;
top: 169px;

background: #000000;


/* house5 */

position: absolute;
width: 31px;
height: 24px;
left: 361px;
top: 129px;

background: #000000;


/* house6 */

position: absolute;
width: 31px;
height: 24px;
left: 557px;
top: 195px;

background: #000000;


/* house7 */

position: absolute;
width: 31px;
height: 24px;
left: 579px;
top: 358px;

background: #000000;


/* house8 */

position: absolute;
width: 31px;
height: 24px;
left: 582px;
top: 566px;

background: #000000;


/* house1 */

position: absolute;
width: 31px;
height: 24px;
left: 222px;
top: 799px;

background: #000000;


/* house9 */

position: absolute;
width: 31px;
height: 24px;
left: 487px;
top: 770px;

background: #000000;


/* resources */

position: absolute;
width: 678px;
height: 822px;
left: 38px;
top: 88px;



/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 588px;
top: 228px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 523px;
top: 198px;

background: #44FF00;


/* market */

position: absolute;
width: 9px;
height: 9px;
left: 287px;
top: 373px;

background: #FF0000;


/* water */

position: absolute;
width: 9px;
height: 9px;
left: 388px;
top: 590px;

background: #68A7FF;


/* honey */

position: absolute;
width: 9px;
height: 9px;
left: 345px;
top: 702px;

background: #FFD500;


/* honey */

position: absolute;
width: 9px;
height: 9px;
left: 499px;
top: 296px;

background: #FFD500;


/* honey */

position: absolute;
width: 9px;
height: 9px;
left: 217px;
top: 638px;

background: #FFD500;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 230px;
top: 843px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 285px;
top: 802px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 443px;
top: 810px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 276px;
top: 647px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 513px;
top: 815px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 541px;
top: 555px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 601px;
top: 397px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 586px;
top: 897px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 305px;
top: 901px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 83px;
top: 745px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 70px;
top: 711px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 38px;
top: 373px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 97px;
top: 404px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 65px;
top: 388px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 268px;
top: 88px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 486px;
top: 114px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 414px;
top: 226px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 523px;
top: 492px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 667px;
top: 836px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 707px;
top: 369px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 539px;
top: 364px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 424px;
top: 494px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 461px;
top: 451px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 450px;
top: 388px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 384px;
top: 507px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 309px;
top: 496px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 264px;
top: 451px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 259px;
top: 404px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 625px;
top: 590px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 134px;
top: 525px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 192px;
top: 349px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 230px;
top: 184px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 101px;
top: 575px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 123px;
top: 368px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 154px;
top: 194px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 414px;
top: 141px;

background: #44FF00;


/* garden */

position: absolute;
width: 9px;
height: 9px;
left: 405px;
top: 169px;

background: #44FF00;


/* smoke stack */

position: absolute;
width: 546px;
height: 686px;
left: 84px;
top: 43px;



/* smoke */

position: absolute;
width: 9px;
height: 9px;
left: 226px;
top: 676px;

background: #000000;


/* smoke */

position: absolute;
width: 9px;
height: 9px;
left: 565px;
top: 720px;

background: #000000;


/* smoke */

position: absolute;
width: 9px;
height: 9px;
left: 304px;
top: 43px;

background: #000000;


/* smoke */

position: absolute;
width: 9px;
height: 9px;
left: 84px;
top: 247px;

background: #000000;


/* smoke */

position: absolute;
width: 9px;
height: 9px;
left: 621px;
top: 109px;

background: #000000;
